# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inception',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=32)),
                ('port', models.IntegerField()),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('isSelected', models.IntegerField()),
            ],
        ),
    ]
